all:	build run
build: 	
	g++ main.cpp -Wall -ggdb3 -o main
run:	
	#./main hamlet.txt > output.txt
	./main
reader: reader.cpp
	g++ reader.cpp -Wall -ggdb3 -o reader
writer:	writer.cpp
	g++ writer.cpp -Wall -ggdb3 -o writer